version: '3'
services:
  api:
    container_name: strider-api
    build:
      context: ./
      dockerfile:  Dockerfile
    env_file:
      - .env
  db:
    container_name: strider-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: strider
    volumes:
      - data:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql
    command: mysqld --init-file="/data/application/init.sql"
    ports:
      - "3306:3306"

volumes:
  data:
