version: '3'
services:
  api:
    container_name: strider-api
    build:
      context: ./
      dockerfile:  Dockerfile
    env_file:
      - .env
  db:
    container_name: strider-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: strider
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local