version: '3.7'
services:
  api:
    build: .
    container_name: strider-api
    restart: unless-stopped
    ports:
     - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - appmysql
  db:
    container_name: strider-database
    image: mysql:latest
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: strider
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    networks:
      - appmysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:

  
networks:
  appmysql:
    driver: bridge